---
- name: install redis
  apt:
    name: redis-server
    state: present

- name: install redis config
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: "{{ redis_conf_file_group }}"
    mode: 0640
  notify: restart redis

- name: watch redis with monit
  template:
    src: redis-monit.j2
    dest: /etc/monit/conf.d/redis
    mode: 0600
  notify: reload monit

- name: Open redis port to deployed machines only
  ufw:
    rule: allow
    port: "{{ redis_port }}"
    src: "{{ item }}"
    proto: tcp
  with_items: "{{ redis_permitted_client_ips }}"
  notify: restart ufw
