---
- name: Collect minimal facts for use by geerlingguy.redis role
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - min

- name: custom redis install
  include_role:
    name: geerlingguy.redis
  vars:
    redis_bind_interface: "{{ redis_custom_bind_interface }}"
    redis_requirepass: "{{ redis_password }}"

- name: ensure permissions of redis conf file
  file:
    path: /etc/redis/redis.conf
    owner: redis
    group: "{{ redis_conf_file_group }}"
    mode: 0640

- name: watch redis with monit
  template:
    src: redis-monit.j2
    dest: /etc/monit/conf.d/redis
    mode: 0600
  notify: reload monit

- name: Open redis port to deployed machines only
  ufw:
    rule: allow
    port: "{{ redis_port }}"
    src: "{{ item }}"
    proto: tcp
  with_items: "{{ redis_permitted_client_ips }}"
  notify: restart ufw
