---
- name: restart ufw
  systemd:
    name: ufw
    enabled: yes
    state: restarted

- name: restart redis
  systemd:
    name: "{{ redis_service_name }}"
    enabled: yes
    daemon_reload: yes
    state: restarted
